<a href="https://colab.research.google.com/github/fox-n/ML_course_homeworks/blob/main/Copy_of_HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [2]:
import numpy as np
import matplotlib.pyplot as plt


In [3]:
vector = np.random.rand(1,10)
print(f'Вектор:\n {vector}\n')
print(f'Розмір вектора: {vector.shape}')

Вектор:
 [[0.02194667 0.04901372 0.26331456 0.92304707 0.80987032 0.7538559
  0.20191093 0.08267408 0.60729096 0.19377394]]

Розмір вектора: (1, 10)


In [4]:
matrix = np.array([[1, 14, 17],
           [20, 23, 26],
           [29, 32, 35]])
print(f'Матриця:\n {matrix}\n')
print(f'Розмір матриці:\n {matrix.shape}')

Матриця:
 [[ 1 14 17]
 [20 23 26]
 [29 32 35]]

Розмір матриці:
 (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [5]:
#1 Додавання числа 10 до кожного значення вектора і округлення до 2го знаку
print(f'Вектор з новими значеннями:\n {np.round((vector + 10), 2)}')


Вектор з новими значеннями:
 [[10.02 10.05 10.26 10.92 10.81 10.75 10.2  10.08 10.61 10.19]]


In [6]:
#2 Множення кожного елементу матриці на 2
print(f'Матриця з новими значеннями:\n {matrix * 2}')

Матриця з новими значеннями:
 [[ 2 28 34]
 [40 46 52]
 [58 64 70]]


In [7]:
#3 Створення нового вектору з квадратами vector
new_vector = np.square(vector)
print(f'Вектор з квадратами:\n {new_vector}')

Вектор з квадратами:
 [[4.81656153e-04 2.40234499e-03 6.93345581e-02 8.52015896e-01
  6.55889932e-01 5.68298724e-01 4.07680235e-02 6.83500284e-03
  3.68802313e-01 3.75483411e-02]]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [8]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [9]:
#1 Множення матриць:

result_matrix = np.dot(B, A)
print(f'Результуюча матриця:\n {result_matrix}')

Результуюча матриця:
 [[0.7281 0.5202]
 [0.2034 0.2846]]


In [12]:
print(f'Результат множення матриці result_matrix на матрицю С:\n{np.dot(result_matrix, C)}')

Результат множення матриці result_matrix на матрицю С:
[[0.5202]
 [0.2846]]


In [13]:
print(f'Результат множення матриці result_matrix на матрицю D:\n{np.dot(result_matrix, D)}')

Результат множення матриці result_matrix на матрицю D:
[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [15]:
print(f'Транспонована матриця result_matrix:\n {result_matrix.T}')

Транспонована матриця result_matrix:
 [[0.7281 0.2034]
 [0.5202 0.2846]]


In [41]:


print(f'Vector\n{vector}\n Розмір vector {vector.shape}')

print(f'Транспонований vector\n {vector.T}\n Розмір {vector.T.shape}')

#Збільшення розмірності вектору

column_vector = np.expand_dims(vector, axis = 1)

print(f'Column_vector\n {column_vector}\n Розмірність {column_vector.shape}')

print(f'Транспонований Column_vector\n {column_vector.T}\n Розмірність {column_vector.T.shape}')





Vector
[[0.02194667 0.04901372 0.26331456 0.92304707 0.80987032 0.7538559
  0.20191093 0.08267408 0.60729096 0.19377394]]
 Розмір vector (1, 10)
Транспонований vector
 [[0.02194667]
 [0.04901372]
 [0.26331456]
 [0.92304707]
 [0.80987032]
 [0.7538559 ]
 [0.20191093]
 [0.08267408]
 [0.60729096]
 [0.19377394]]
 Розмір (10, 1)
Column_vector
 [[[0.02194667 0.04901372 0.26331456 0.92304707 0.80987032 0.7538559
   0.20191093 0.08267408 0.60729096 0.19377394]]]
 Розмірність (1, 1, 10)
Транспонований Column_vector
 [[[0.02194667]]

 [[0.04901372]]

 [[0.26331456]]

 [[0.92304707]]

 [[0.80987032]]

 [[0.7538559 ]]

 [[0.20191093]]

 [[0.08267408]]

 [[0.60729096]]

 [[0.19377394]]]
 Розмірність (10, 1, 1)


Висновок: операція numpy.expand_dims збільшує розмірність вектора